/*
 * File: app/store/beamsStore.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.store.beamsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'RFID_Tag_Locator_Service.model.beamsModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'beamsStore',
            model: 'RFID_Tag_Locator_Service.model.beamsModel',
            data: [
                {
                    AntennaId: 21,
                    AntennaName: 'Beam22',
                    Rssi: -50,
                    ScaledRssi: -50,
                    EPC: '   ',
                    Active: true,
                    TagDetected: false
                },
                {
                    AntennaId: 23,
                    AntennaName: 'Beam24',
                    Rssi: -60,
                    ScaledRssi: -60,
                    EPC: '  ',
                    Active: true,
                    TagDetected: false
                },
                {
                    AntennaId: 25,
                    AntennaName: 'Beam26',
                    Rssi: -55,
                    ScaledRssi: -55,
                    EPC: '  ',
                    Active: false,
                    TagDetected: false
                },
                {
                    AntennaId: 27,
                    AntennaName: 'Beam28',
                    Rssi: -66,
                    ScaledRssi: -66,
                    EPC: '  ',
                    Active: true,
                    TagDetected: false
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});