/*
 * File: app/store/BfaConfigStore.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.store.BfaConfigStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'BfaConfigStore',
            data: [
                {
                    Name: 'none',
                    SerialNo: 'none',
                    IpAddress: 'none',
                    TxLevel: 'none',
                    Orientation: 'none'
                }
            ],
            fields: [
                {
                    type: 'string',
                    name: 'Name'
                },
                {
                    type: 'string',
                    name: 'SerialNo'
                },
                {
                    type: 'string',
                    name: 'IpAddress'
                },
                {
                    type: 'int',
                    name: 'TxLevel'
                },
                {
                    type: 'string',
                    name: 'Orientation'
                },
                {
                    type: 'string',
                    defaultValue: 'beam8',
                    name: 'TopBeam'
                },
                {
                    type: 'string',
                    defaultValue: 'beam14',
                    name: 'BottomBeam'
                }
            ]
        }, cfg)]);
    }
});