/*
 * File: app/store/FloorLayoutStore.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.store.FloorLayoutStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json',
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'FloorLayoutStore',
            data: [
                {
                    floorName: 'Default'
                },
                {
                    floorName: 'Hallway_RIM'
                },
                {
                    floorName: 'Lobby_Main'
                },
                {
                    floorName: 'Luggage_Conveyor'
                },
                {
                    floorName: 'Passage_Main'
                },
                {
                    floorName: 'Stock_Room'
                }
            ],
            proxy: {
                type: 'memory',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'floorName'
                }
            ]
        }, cfg)]);
    }
});