/*
 * File: app/store/InventoryStore.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.store.InventoryStore', {
    extend: 'Ext.data.Store',

    requires: [
        'RFID_Tag_Locator_Service.model.InventoryModel',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json',
        'Ext.util.Sorter'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'InventoryStore',
            autoLoad: false,
            model: 'RFID_Tag_Locator_Service.model.InventoryModel',
            proxy: {
                type: 'memory',
                reader: {
                    type: 'json',
                    rootProperty: 'root',
                    record: 'Payload'
                }
            },
            sorters: [
                {
                    direction: 'DESC',
                    id: 'InventoryEpcSorter',
                    property: 'EPC',
                    root: 'data'
                },
                {
                    direction: 'DESC',
                    id: 'InventoryRssiSorter',
                    property: 'ScaledRssi',
                    root: 'data'
                }
            ]
        }, cfg)]);
    }
});