/*
 * File: app/store/TagStore.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.store.TagStore', {
    extend: 'Ext.data.Store',

    requires: [
        'RFID_Tag_Locator_Service.model.TagModel',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'TagStore',
            model: 'RFID_Tag_Locator_Service.model.TagModel',
            data: [
                {
                    TagID: 1,
                    TagEPC: '8000000006C526E901DBF1D8',
                    DetectTag: false
                },
                {
                    TagID: 2,
                    TagEPC: '8000000006C525C801DBF1D8',
                    DetectTag: false
                },
                {
                    TagID: 3,
                    TagEPC: '8000000006C525EF01DBF1D8',
                    DetectTag: false
                },
                {
                    TagID: 4,
                    TagEPC: '8000000006DA37FE001ECFAB',
                    DetectTag: false
                },
                {
                    TagID: 5,
                    TagEPC: '8000000006C526F301DBF1D8',
                    DetectTag: false
                },
                {
                    TagID: 6,
                    TagEPC: '8000000006C50E91785A6ADE',
                    DetectTag: false
                },
                {
                    TagID: 7,
                    TagEPC: '8000000006DB6F237859596E',
                    DetectTag: false
                },
                {
                    TagID: 8,
                    TagEPC: '8000000006C50E99785A6ADE',
                    DetectTag: false
                },
                {
                    TagID: 9,
                    TagEPC: '8000000006DB6F687859807E',
                    DetectTag: false
                }
            ],
            proxy: {
                type: 'memory',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});