/*
 * File: app/model/BFAs.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.model.BFAs', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Number',
        'Ext.data.field.Boolean'
    ],


    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'string',
            name: 'display_name'
        },
        {
            type: 'float',
            name: 'x_loc'
        },
        {
            type: 'float',
            name: 'y_loc'
        },
        {
            type: 'int',
            name: 'tx_level'
        },
        {
            type: 'boolean',
            name: 'status'
        },
        {
            type: 'string',
            name: 'ip_address'
        },
        {
            type: 'string',
            name: 'area'
        }
    ]

});