/*
 * File: app/view/beam.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.view.beam', {
    extend: 'Ext.draw.Container',
    alias: 'widget.beam',

    requires: [
        'RFID_Tag_Locator_Service.view.beamViewModel',
        'RFID_Tag_Locator_Service.view.beamViewController'
    ],

    controller: 'beam',
    viewModel: {
        type: 'beam'
    },
    height: 500,
    hidden: true,
    itemId: 'beam_class_item_id',
    style: '',
    width: 550,
    draggable: true,
    hideAnimation: 'fadeOut',
    maxHeight: 500,
    maxWidth: 550,
    minHeight: 500,
    minWidth: 550,
    showAnimation: 'fade',
    sprites: [
        {
            surface: 'tagSurface',
            type: 'circle',
            fill: 'red',
            radius: 10,
            opacity: 0.0,
            shadowCls: 'tag-shadow',
            x: 225,
            y: 250
        },
        {
            surface: 'mainSurface',
            type: 'circle',
            fill: 'green',
            opacity: 0.0,
            radius: 200,
            x: 225,
            y: 250
        },
        {
            surface: 'QuadrantSurface',
            type: 'circle',
            fill: '#34cdeb',
            radius: 220,
            opacity: 0.0,
            shadowCls: 'tag-shadow',
            x: 225,
            y: 250
        }
    ],

    listeners: {
        beforeshow: 'onBeam_class_item_idBeforeShow'
    }

});