/*
 * File: app/view/beamsGrid.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.view.beamsGrid', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.beamsgrid',

    requires: [
        'RFID_Tag_Locator_Service.view.beamsGridViewModel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Check'
    ],

    viewModel: {
        type: 'beamsgrid'
    },
    border: true,
    height: '100%',
    itemId: 'beamsGrid',
    width: 560,
    margin: '0 0 0 0',
    maxWidth: 560,
    minWidth: 560,
    manageBorders: true,
    store: 'beamsStore',

    columns: [
        {
            xtype: 'gridcolumn',
            width: 75,
            maxWidth: 75,
            minWidth: 75,
            align: 'center',
            dataIndex: 'AntennaName',
            text: 'Beam'
        },
        {
            xtype: 'numbercolumn',
            width: 70,
            minWidth: 70,
            align: 'center',
            computedWidth: 70,
            dataIndex: 'Rssi',
            defaultWidth: 70,
            text: 'RSSI'
        },
        {
            xtype: 'checkcolumn',
            width: 120,
            maxWidth: 120,
            minWidth: 120,
            userSelectable: true,
            computedWidth: 120,
            dataIndex: 'TagDetected',
            defaultWidth: 120,
            text: 'Tag Detected'
        },
        {
            xtype: 'gridcolumn',
            width: 300,
            maxWidth: 300,
            minWidth: 300,
            align: 'center',
            defaultWidth: 300,
            text: 'EPC'
        }
    ]

});