/*
 * File: app/view/beamViewController.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.view.beamViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.beam',

    statics: {
        surface: function() {
            beam24_1.add({
                type: 'rect',
                x: 50,
                y: 50,
                width: 300,
                height: 300,
                fillStyle: '#1F6D91'
            });
            beam24_1.renderFrame();
        }
    },

    onBeam_class_item_idBeforeShow: function(component, eOpts) {
        component.getSurface('mainSurface').hide();
        component.getSurface('tagSurface').hide();
    }

});