/*
 * File: app/view/BfaSettingsConfig.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.view.BfaSettingsConfig', {
    extend: 'Ext.field.Panel',
    alias: 'widget.bfasettingsconfig',

    requires: [
        'RFID_Tag_Locator_Service.view.BfaSettingsConfigViewModel',
        'Ext.field.ComboBox',
        'Ext.field.RadioGroup',
        'Ext.field.Radio',
        'Ext.Button'
    ],

    viewModel: {
        type: 'bfasettingsconfig'
    },
    border: true,
    height: 100,
    id: 'BfaSettingsConfig',
    itemId: 'BfaSettingsConfig',
    shadow: true,
    width: 1420,
    docked: 'top',
    margin: '10, 10, 10, 50',
    maxHeight: 100,
    maxWidth: 1420,
    minHeight: 100,
    minWidth: 1420,
    scrollable: false,
    layout: 'hbox',
    header: true,
    title: 'BFA Settings',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'textfield',
            border: true,
            height: 'auto',
            id: 'bfaName',
            itemId: 'mytextfield',
            style: '',
            width: 250,
            displayed: true,
            margin: 10,
            maxHeight: 'auto',
            maxWidth: 250,
            minHeight: 'auto',
            minWidth: 250,
            label: 'BFA Name:',
            labelMinWidth: 80,
            labelWidth: 80,
            listeners: {
                change: 'onBfaNameChange'
            }
        },
        {
            xtype: 'textfield',
            border: true,
            height: 'auto',
            id: 'bfaSerial',
            itemId: 'bfaSerial',
            style: '',
            width: 250,
            displayed: true,
            margin: 10,
            maxHeight: 'auto',
            maxWidth: 250,
            minHeight: 'auto',
            minWidth: 250,
            label: 'Serial No.',
            labelMinWidth: 70,
            labelWidth: 70,
            listeners: {
                change: 'onBfaSerialChange'
            }
        },
        {
            xtype: 'textfield',
            border: true,
            height: 'auto',
            id: 'bfaIpAddress',
            itemId: 'bfaIpAddress',
            style: '',
            width: 250,
            displayed: true,
            margin: 10,
            maxHeight: 'auto',
            maxWidth: 250,
            minHeight: 'auto',
            minWidth: 250,
            label: 'IP Address',
            labelMinWidth: 80,
            labelWidth: 80,
            listeners: {
                change: 'onBfaIpAddressChange'
            }
        },
        {
            xtype: 'combobox',
            height: 35,
            hidden: false,
            id: 'bfaTxLevel',
            itemId: 'bfaTxLevel',
            width: 170,
            displayed: true,
            margin: 10,
            maxHeight: 35,
            maxWidth: 170,
            minHeight: 35,
            minWidth: 170,
            label: 'Tx Level',
            labelMinWidth: 70,
            labelWidth: 70,
            editable: false,
            placeholder: '0 = max',
            textAlign: 'center',
            displayField: 'name',
            store: [
                {
                    id: 0,
                    name: '0'
                },
                {
                    id: 1,
                    name: '1'
                },
                {
                    id: 2,
                    name: '2'
                },
                {
                    id: 3,
                    name: '3'
                },
                {
                    id: 4,
                    name: '4'
                },
                {
                    id: 5,
                    name: '5'
                },
                {
                    id: 6,
                    name: '6'
                },
                {
                    id: 7,
                    name: '7'
                },
                {
                    id: 8,
                    name: '8'
                },
                {
                    id: 9,
                    name: '9'
                },
                {
                    id: 10,
                    name: '10'
                }
            ],
            queryMode: 'local',
            listeners: {
                change: 'onBfaTxLevelChange'
            }
        },
        {
            xtype: 'radiogroup',
            height: 30,
            itemId: 'myradiogroup',
            width: 300,
            margin: '10, 10, 10, 40',
            maxHeight: 30,
            maxWidth: 300,
            minHeight: 30,
            minWidth: 300,
            label: 'Top side of BFA :',
            labelMinWidth: 110,
            labelWidth: 110,
            items: [
                {
                    xtype: 'radio',
                    name: 'zone',
                    width: 90,
                    maxWidth: 90,
                    minWidth: 90,
                    label: 'In Zone',
                    value: 'In'
                },
                {
                    xtype: 'radio',
                    name: 'zone',
                    width: 90,
                    maxWidth: 90,
                    minWidth: 90,
                    label: 'Out Zone',
                    value: 'Out'
                }
            ],
            listeners: {
                change: 'onMyradiogroupChange'
            }
        },
        {
            xtype: 'button',
            handler: function(button, e) {
                var mqttController = Ext.getApplication().getController('MqttController');
                mqttController.connectToMqtt();
                var bfaBar 	= Ext.getCmp('bfaBar');

            },
            width: 70,
            maxWidth: 70,
            minWidth: 70,
            text: 'Done'
        }
    ],

    onBfaNameChange: function(field, newValue, oldValue, eOpts) {
        var bfaConfigData = Ext.data.StoreManager.lookup('BfaConfigStore').getAt(0);
        bfaConfigData.set('Name', newValue);
        console.log('BFA Name set to :  ' + bfaConfigData.get('Name'));
        var bfaBar = Ext.getCmp('bfaBar');
        bfaBar.setTitle('BFA :    ' + newValue);

    },

    onBfaSerialChange: function(field, newValue, oldValue, eOpts) {
        var bfaConfigData = Ext.data.StoreManager.lookup('BfaConfigStore').getAt(0);
        bfaConfigData.set('SerialNo', newValue);
        console.log('BFA Serial No set to :  ' + bfaConfigData.get('SerialNo'));
    },

    onBfaIpAddressChange: function(field, newValue, oldValue, eOpts) {
        var bfaConfigData = Ext.data.StoreManager.lookup('BfaConfigStore').getAt(0);
        bfaConfigData.set('IpAddress', newValue);
        console.log('BFA Ip Address set to :  ' + bfaConfigData.get('IpAddress'));
    },

    onBfaTxLevelChange: function(combobox, newValue, oldValue, eOpts) {
        var bfaConfigData = Ext.data.StoreManager.lookup('BfaConfigStore').getAt(0);
        bfaConfigData.set('TxLevel', newValue);
        console.log('TxLevel set to :  ' + bfaConfigData.get('TxLevel'));
    },

    onMyradiogroupChange: function(field, newValue, oldValue, eOpts) {
        var bfaConfigData = Ext.data.StoreManager.lookup('BfaConfigStore').getAt(0);
        bfaConfigData.set('Orientation', newValue);
        console.log('BFA Orientation set to :  ' + bfaConfigData.get('Orientation'));
    }

});