/*
 * File: app/view/DirectionMapPanel.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.view.DirectionMapPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.directionmappanel',

    requires: [
        'RFID_Tag_Locator_Service.view.DirectionMapPanelViewModel',
        'RFID_Tag_Locator_Service.view.beam',
        'Ext.TitleBar',
        'Ext.draw.Container',
        'Ext.Img',
        'Ext.Panel'
    ],

    viewModel: {
        type: 'directionmappanel'
    },
    constrainAlign: 'searchFloor',
    height: '100%',
    id: 'DirectionMapPanel',
    itemId: 'searchPanel',
    width: 500,
    docked: 'left',
    margin: '10 10 10 100',
    maxHeight: '100%',
    maxWidth: 500,
    minHeight: '100%',
    minWidth: 500,
    layout: 'vbox',
    header: false,
    minButtonWidth: 500,
    title: 'search_main_panel',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'titlebar',
            height: 50,
            id: 'bfaBar',
            itemId: 'bfaBar',
            width: 500,
            margin: '10 0 10 0',
            maxHeight: 50,
            maxWidth: 500,
            minHeight: 50,
            minWidth: 500,
            title: 'BFA:',
            bind: {
                border: 'true'
            }
        },
        {
            xtype: 'beam',
            constrainAlign: '#searchFloor',
            hidden: true,
            id: 'beam26Sim',
            itemId: 'beam26Sim',
            relative: true,
            shadow: false,
            width: 450,
            displayed: true,
            draggable: true,
            left: 40,
            maxWidth: 450,
            minWidth: 450,
            top: 15
        },
        {
            xtype: 'image',
            height: 120,
            hidden: true,
            id: 'outArrow',
            shadow: false,
            width: 100,
            displayed: true,
            left: 330,
            maxHeight: 120,
            maxWidth: 100,
            minHeight: 120,
            minWidth: 100,
            top: 250,
            src: 'images/arrow/up-arrow-shadow.png',
            listeners: {
                beforeshow: 'onUpArrowBeforeShow'
            }
        },
        {
            xtype: 'image',
            height: 120,
            hidden: true,
            id: 'inArrow',
            shadow: false,
            width: 100,
            displayed: true,
            left: 65,
            maxHeight: 120,
            maxWidth: 100,
            minHeight: 120,
            minWidth: 100,
            top: 250,
            src: 'images/arrow/down-arrow-shadow.png',
            listeners: {
                beforeshow: 'onDownArrowBeforeShow'
            }
        },
        {
            xtype: 'image',
            height: 500,
            id: 'searchFloor',
            style: 'opacity: 0.6;',
            width: 500,
            maxHeight: 500,
            maxWidth: 500,
            minHeight: 500,
            minWidth: 500,
            src: 'images/floor_layout/Default.png'
        },
        {
            xtype: 'panel',
            layout: 'hbox',
            header: false,
            title: 'My Panel',
            items: [
                {
                    xtype: 'titlebar',
                    height: 40,
                    id: 'directionBarIn',
                    style: 'background-color: #369c53;',
                    width: 240,
                    margin: '10 0 0 0',
                    maxHeight: 40,
                    maxWidth: 240,
                    minHeight: 40,
                    minWidth: 240,
                    title: 'IN :',
                    bind: {
                        border: 'true'
                    }
                },
                {
                    xtype: 'titlebar',
                    height: 40,
                    id: 'directionBarOut',
                    style: 'background-color: #e06e58;',
                    width: 240,
                    margin: '10 0 0 20',
                    maxHeight: 40,
                    maxWidth: 240,
                    minHeight: 40,
                    minWidth: 240,
                    title: 'OUT :',
                    bind: {
                        border: 'true'
                    }
                }
            ]
        },
        {
            xtype: 'image',
            height: 120,
            id: 'BFA',
            shadow: true,
            style: '',
            width: 120,
            draggable: true,
            html: '<div style="text-align:center;margin-top: 5px; font-size: 10px;">Top Side</div>',
            left: 190,
            maxHeight: 120,
            maxWidth: 120,
            minHeight: 120,
            minWidth: 120,
            top: 250,
            src: 'images/bfa/BFA_BRADY2.png'
        }
    ],

    onUpArrowBeforeShow: function(component, eOpts) {
        component.hide();
    },

    onDownArrowBeforeShow: function(component, eOpts) {
        component.hide();
    }

});