/*
 * File: app/view/InventoryGrid.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.view.InventoryGrid', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.inventorygrid',

    requires: [
        'RFID_Tag_Locator_Service.view.InventoryGridViewModel',
        'Ext.grid.column.Number'
    ],

    viewModel: {
        type: 'inventorygrid'
    },
    height: '100%',
    id: 'InventoryGrid',
    itemId: 'InventoryGrid',
    width: '100%',
    store: 'InventoryStore',

    columns: [
        {
            xtype: 'gridcolumn',
            width: 250,
            maxWidth: 250,
            minWidth: 250,
            computedWidth: 250,
            dataIndex: 'EPC',
            defaultWidth: 250,
            text: 'EPC'
        },
        {
            xtype: 'numbercolumn',
            width: 70,
            maxWidth: 70,
            minWidth: 70,
            computedWidth: 70,
            dataIndex: 'AntennaId',
            defaultWidth: 70,
            text: 'Beam Id'
        },
        {
            xtype: 'gridcolumn',
            width: 100,
            maxWidth: 100,
            minWidth: 100,
            computedWidth: 100,
            dataIndex: 'AntennaName',
            text: 'Beam Name'
        },
        {
            xtype: 'gridcolumn',
            width: 140,
            maxWidth: 140,
            minWidth: 140,
            computedWidth: 140,
            dataIndex: 'ScaledRssi',
            defaultWidth: 140,
            text: 'Scaled RSSI'
        }
    ]

});