/*
 * File: app/view/MainRTLS.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.view.MainRTLS', {
    extend: 'Ext.Container',
    alias: 'widget.MainRTLS',

    alternateClassName: [
        'MainRTLS'
    ],
    requires: [
        'RFID_Tag_Locator_Service.view.MainRTLSViewModel',
        'RFID_Tag_Locator_Service.view.MainRTLSViewController',
        'RFID_Tag_Locator_Service.view.DirectionMapPanel',
        'RFID_Tag_Locator_Service.view.DirectionPanel',
        'RFID_Tag_Locator_Service.view.BfaSettingsConfig',
        'Ext.TitleBar',
        'Ext.tab.Panel',
        'Ext.Img',
        'Ext.field.Panel',
        'Ext.field.ComboBox',
        'Ext.panel.Accordion'
    ],

    controller: 'mainrtls',
    viewModel: {
        type: 'mainrtls'
    },
    id: 'mainView',
    itemId: 'mainView',
    layout: 'vbox',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'titlebar',
            height: 50,
            style: 'box-shadow: rgb(38, 57, 77) 0px 20px 30px -10px; background-color:  #0066cc',
            docked: 'top',
            margin: '0 0 5 0',
            maxHeight: 50,
            minHeight: 50,
            title: 'RFID Tag Direction Finder   : : : : :    In & Out Zones'
        },
        {
            xtype: 'tabpanel',
            height: '100%',
            id: 'mainTab',
            itemId: 'mainTab',
            margin: '0 0 0 0',
            maxHeight: '100%',
            minHeight: '100%',
            layout: {
                type: 'card',
                animation: 'fade',
                'animation.duration': 20
            },
            items: [
                {
                    xtype: 'container',
                    docked: 'top',
                    html: '',
                    margin: '1 1 1 1',
                    layout: 'center'
                },
                {
                    xtype: 'container',
                    title: 'Home',
                    iconCls: 'x-fa fa-home',
                    margin: '1 1 1 1',
                    items: [
                        {
                            xtype: 'panel',
                            height: '100%',
                            width: '100%',
                            maxHeight: '100%',
                            maxWidth: '100%',
                            minHeight: '100%',
                            minWidth: '100%',
                            bodyPadding: 15,
                            header: false,
                            title: 'My Panel',
                            layout: {
                                type: 'hbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'titlebar',
                                    height: 40,
                                    id: 'directionBar1',
                                    style: 'position: absolute;  top: 60%',
                                    width: 300,
                                    maxHeight: 40,
                                    maxWidth: 300,
                                    minHeight: 40,
                                    minWidth: 300,
                                    title: 'Version:  Alpha 0.2',
                                    bind: {
                                        border: 'true'
                                    }
                                },
                                {
                                    xtype: 'image',
                                    height: 171,
                                    shadow: false,
                                    style: 'width: 400px; height: 400px; position: absolute;   top: 10%;',
                                    width: '',
                                    displayed: true,
                                    src: 'images/home_page/nordicIdLogo1.png'
                                },
                                {
                                    xtype: 'image',
                                    hidden: false,
                                    style: 'width: 800px; height: 600px; opacity: 0.2; 70%; filter: position: absolute;   top: 0%;',
                                    displayed: true,
                                    src: 'images/home_page/inOutZone.png'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    title: 'Direction Tracking',
                    iconCls: 'x-fa fa-search',
                    border: false,
                    hidden: false,
                    id: 'directionTab',
                    itemId: 'directionTab',
                    shadow: false,
                    width: '100%',
                    displayed: true,
                    html: '',
                    margin: '1 1 1 1 ',
                    maxWidth: '100%',
                    minWidth: '100%',
                    scrollable: true,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'panel',
                            scrollable: true,
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'directionmappanel',
                                    itemId: 'directionmappanel',
                                    margin: '10 10 10 50'
                                },
                                {
                                    xtype: 'directionpanel',
                                    hidden: false
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    title: 'Settings and Configurations',
                    iconCls: 'x-fa fa-search',
                    border: false,
                    hidden: false,
                    id: 'settingsTab',
                    itemId: 'settingsTab',
                    shadow: false,
                    width: '100%',
                    displayed: true,
                    html: '',
                    margin: '1 1 1 1 ',
                    maxWidth: '100%',
                    minWidth: '100%',
                    scrollable: true,
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'panel',
                            scrollable: false,
                            layout: 'vbox',
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'bfasettingsconfig',
                                    border: false
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 50,
                            hidden: false,
                            shadow: true,
                            width: 700,
                            margin: '10 0 0 50',
                            maxHeight: 350,
                            maxWidth: 700,
                            minHeight: 350,
                            minWidth: 700,
                            manageBorders: false,
                            header: true,
                            title: 'Floor Layout',
                            layout: {
                                type: 'hbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'image',
                                    border: true,
                                    height: 250,
                                    hideMode: 'visibility',
                                    id: 'floorThumbnail',
                                    width: 250,
                                    hideAnimation: 'fadeOut',
                                    margin: '20 20 20 20',
                                    maxHeight: 250,
                                    maxWidth: 250,
                                    minHeight: 50,
                                    minWidth: 250,
                                    showAnimation: 'fadeIn',
                                    src: 'images/floor_layout/Default.png'
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'floorSelection',
                                    itemId: 'mycombobox1',
                                    width: 300,
                                    displayed: true,
                                    maxWidth: 300,
                                    minWidth: 300,
                                    label: 'Floor Layout :',
                                    labelMinWidth: 100,
                                    labelWidth: 100,
                                    displayField: 'floorName',
                                    store: 'FloorLayoutStore',
                                    valueField: 'floorName',
                                    listeners: {
                                        change: 'onFloorSelectionChange'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    title: 'Logs',
                    iconCls: 'x-fa fa-edit',
                    hidden: true,
                    margin: '1 1 1 1',
                    items: [
                        {
                            xtype: 'accordion',
                            header: false,
                            title: 'My Panel'
                        }
                    ]
                }
            ]
        }
    ],

    onFloorSelectionChange: function(combobox, newValue, oldValue, eOpts) {
        var floorThumbnail = Ext.getCmp('floorThumbnail');
        var searchFloor = Ext.getCmp('searchFloor');
        floorThumbnail.setSrc('images/floor_layout/' + newValue + '.png');
        searchFloor.setSrc('images/floor_layout/' + newValue + '.png');
    },

    initialize: function() {
        this.callParent();
    }

});