/*
 * File: app/view/MainRTLSViewController.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.view.MainRTLSViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mainrtls',

    showView: function(view) {
        var container = this.getReferences().display;
        container.setActiveItem(this.lookupReference(view));
    },

    setButtonDisable: function(disable) {
        var toolbar = this.getReferences().toolbar,
            editButton = toolbar.down('#editButton'),
            removeButton = toolbar.down('#removeButton');

        if (disable) {
            editButton.disable();
            removeButton.disable();
        }
        else {
            editButton.enable();
            removeButton.enable();
        }
    }

});