/*
 * File: app/view/MoviePanel.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.view.MoviePanel', {
    extend: 'Ext.Panel',
    alias: 'widget.moviepanel',

    requires: [
        'Ext.Component'
    ],

    height: 500,
    id: 'MoviePanel',
    width: 1060,
    maxHeight: 500,
    maxWidth: 500,
    minHeight: 500,
    minWidth: 500,
    scrollable: false,
    layout: 'fit',
    header: false,
    minButtonWidth: 500,
    title: 'My Panel',

    items: [
        {
            xtype: 'component',
            height: 500,
            id: 'VideoFrameClass',
            style: 'border: none;',
            width: 500,
            axisLock: false,
            draggable: false,
            html: '<iframe src="http://192.168.0.81" width="500" height="500"></iframe>',
            maxHeight: 500,
            maxWidth: 500,
            minHeight: 500,
            minWidth: 500,
            modal: false,
            modelValidation: false
        }
    ]

});