/*
 * File: app/view/TagGrid.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.view.TagGrid', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.taggrid',

    requires: [
        'RFID_Tag_Locator_Service.view.TagGridViewModel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Check'
    ],

    viewModel: {
        type: 'taggrid'
    },
    height: '100%',
    id: 'TagGrid',
    width: '100%',
    displayed: true,
    store: 'TagStore',

    columns: [
        {
            xtype: 'numbercolumn',
            width: 100,
            maxWidth: 100,
            minWidth: 100,
            align: 'center',
            computedWidth: 100,
            dataIndex: 'TagID',
            text: 'Tag ID'
        },
        {
            xtype: 'gridcolumn',
            width: 300,
            maxWidth: 300,
            minWidth: 300,
            align: 'center',
            computedWidth: 300,
            dataIndex: 'TagEPC',
            defaultWidth: 300,
            text: 'Tag EPC'
        },
        {
            xtype: 'checkcolumn',
            width: 100,
            maxWidth: 100,
            minWidth: 100,
            computedWidth: 100,
            dataIndex: 'DetectTag',
            text: 'Detect Tag'
        }
    ]

});