/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'BFAs',
        'InventoryModel',
        'InventoryModelMapping',
        'TagModel',
        'beamsModel',
        'DirectionInOutModel',
        'DirectionModel'
    ],
    stores: [
        'BFA_dummy',
        'BFA_dummy1',
        'BFA_dummy2',
        'beamsStore',
        'InventoryStore',
        'TagStore',
        'DirectionInOutStore',
        'DirectionInStore',
        'DirectionOutStore',
        'BfaConfigStore',
        'FloorLayoutStore'
    ],
    views: [
        'MainRTLS',
        'beamsGrid',
        'InventoryGrid',
        'TagGrid',
        'beam',
        'MoviePanel',
        'DirectionPanel',
        'DirectionMapPanel',
        'BfaSettingsConfig'
    ],
    controllers: [
        'MqttController',
        'MyController2',
        'TagDirectionController'
    ],
    name: 'RFID_Tag_Locator_Service',
    title: 'RFID_Tracker',

    launch: function() {
        Ext.create('RFID_Tag_Locator_Service.view.MainRTLS', {fullscreen: true});
    }

});
