/*
 * File: app/controller/MyController2.js
 *
 * This file was generated by Sencha Architect version 4.3.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.8.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.8.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RFID_Tag_Locator_Service.controller.MyController2', {
    extend: 'Ext.app.Controller',

    control: {
        "textfield#epcField": {
            change: 'onEpcFieldChange'
        }
    },

    onEpcFieldChange: function(field, newValue, oldValue, eOpts) {
        var beams = field.up().up().getComponent('searchPanel').getComponent('beam26Sim');
        beams.getSurface('beam26_1').show();
        beams.getSurface('beam26_15').show();
        beams.getSurface('beam26_2').show();
        field.disable();
    }

});